### ISSUE TITLE
Forma del hash de password 

### ISSUE THREAD

**Issue by wicho1001** [mikenieva/learning-guitar-shop#3]
UserSchema.pre('save', function (next) {
  this.password = bcrypt.hashSync(this.password, 10)
  next()
})

Si lo dejamos como Sync tendremos que comparar la contraseña de sigueinte manera(en el momento de la autenticacion)

bcrypt.compareSync(req.headers.password, UserInfo.password)

**Comment by mikenieva** [comment]
Hola Wicho! Revisado.

Existen dos maneras de ejecutarlo. Asíncrono y Síncrono.

La forma en cómo lo redacté en el tutorial está hecho asíncronamente. No sabía que existía el otro método.

Ambos son correctos. Sin embargo, debido a que estamos jugando con mongoose, se sugiere asincronía.

Voy a profundizar pero me genera confianza que haya mucha discusión al respecto.

https://www.abeautifulsite.net/hashing-passwords-with-nodejs-and-bcrypt
http://codetheory.in/using-the-node-js-bcrypt-module-to-hash-and-safely-store-passwords/
https://stackoverflow.com/questions/11605943/async-or-sync-bcrypt-function-to-use-in-node-js-in-order-to-generate-hashes
https://news.ycombinator.com/item?id=11120279

**Comment by wicho1001** [comment]
Pffff, gracias mike por los recursos, estan chidos creo que si hay razon en hacerlo asincronico :+1:  :+1:
